### ISSUE TITLE
Minimal perfect hashing

### ISSUE THREAD

**Issue by dgryski** [demerphq/uni_prop_parser#1]
Did you investigate any of the perfect hashing algorithms?

**Comment by demerphq** [comment]
No, although given the code-footprint of this logic probably we should. Part of the problem is the total key length for all the keys is 67005 bytes (72994 null terminated). My original thinking was that any hash algorithm is going to need to do a final key comparison, so we would need to store all those keys, and then have a hash table with 5989 entries, so the result would still be large. But considering that /this/ code ends up being almost 200k maybe we need to reconsider.

**Comment by dgryski** [comment]
Yes, you'd still need to store the data, but there are options for reducing the size of the generated tables.

I think the best current library is http://cmph.sourceforge.net/ but I don't know if it does compile-time generation or only runtime + serialization.  (You might need another build step.)

The original compress-hash-displace algorithm is pretty straight-forward: I talk about it https://blog.gopheracademy.com/advent-2017/mphf/ and have a small implementation linked.  I would avoid gperf as it's meant for much smaller tables.

**Comment by dgryski** [comment]
A few more comments:  If you know you're always looking up valid properties, you don't need to store the full set of keys to check against at the second.  Second, if lookup is *still* too slow, you could consider constructing a bloom filter from the keys and checking that first based on a small hash (says, mixing the first 4 and last 4 characters of the string) before doing a "full" hash table lookup.  For space usage, minimal perfect hashing (without additional table compression) will use two uint32s per key to store the lookup table.

**Comment by dgryski** [comment]
Do you have benchmark numbers for your current approach vs. a regular Perl hash?

**Comment by demerphq** [comment]
I just pushed mph.pl and related files. I was able to get the required size down to 87% of the combined key lengths to store all the data, including values (integers).

I used the two level construction, using 32-bit fnv for the hash function, combined with a block of key "fragments" chosen by decomposing the keys into two parts, a prefix and suffix. The resulting table is an array of the following struct:

struct mph_meta {
    uint16_t seed2;
    uint16_t pfx;
    uint16_t sfx;
    uint8_t  pfx_len;
    uint8_t  sfx_len;
    uint16_t value;
};

The process is: hash the key with 32-bit fnv, then mod that by the number of keys, to find the seed2. If the seed2 is 0 then there is no match, otherwise we shift the hash right by 8 bits and then xor in the seed2 and then mod that by the number of the keys to find the correct struct for the final comparisons, which compare the prefix, and then the suffix (if there is one), and if all is correct returns the desired value.
So for instance the row below shows that the seed2 for bucket 0 is 2, and the prefix for bucket 0 is stored in the blob at offset 439, and the suffix at offset 4893, and the prefix is 4 chars long and the suffix is 2. If all matches it returns the define ISMIAO

const struct mph_meta const mph[3946] = {
  {     2,   439,  4893,   4,   2, ISMIAO },
  ....
};

Thanks a lot for piping up damian, this was educational, fun, and useful all at once. :-)

BTW, speed is not really a huge concern here, it is more getting a good balance of a small footprint without being horribly slow. (Afaiui)

**Comment by khwilliamson** [comment]
We don't know if we are looking up valid properties, and I'm counting on the code to not accept illegal ones.  Currently it does accept illegal ones.  I don't know if this is a fault of the implementation or the underlying algorithm chosen.

An example is 
isqmark=/a/false

'isqmark' is valid and so is 'isqmark=true', and 'isqmark=false', and several other things that begin 'isqmark=...'.  I don't know which this thinks it is, but it is one of the ones that mean that it is qmark, as opposed to the negation

**Comment by dgryski** [comment]
The construction I pointed to would work as follows:

The full Unicode property name is hashed with fnv. That points to an entry in a `seeds` table. If the seed is negative, it's used as an offset (negated, of course) into a `values` table where the prefix/suffix struct can be to compare with the compressed blob. If the seed is positive, it's used as the seed for a second hash function and the result of that is an entry in the values array.

**Comment by khwilliamson** [comment]
It came to me in a series of dreams last night that what is probably happening is that in the case I mentioned, it hashed to 'isqmark', and that the memcmps are using as the length to look at (to avoid reading past the end of a buffer) just the shortest of their inputs.  Whereas, a preliminary length test to makes sure that the values array entry is the same length as the input would fix this

I haven't looked at this code in any detail, merely just scanning it, and I remember seeing some memcmps(),.  The answers that come to me in my dreams are almost always correct, not not always.

**Comment by khwilliamson** [comment]
Having now looked at the generated code,  my intuition was wrong in the specifics, but correct in that there is a missing length check.  I haven't looked at how the tables are generated, but there are an infinite number of possible input strings that will hash to any given bucket.  And all but the desired one need to be excluded.  Hopefully the tables are constructed so that no other string of length n can end up in the same bucket as our desired string of length n.  But we need to exclude those of different lengths.  Adding this conditional to the test that determines if the lookup found anything causes all my tests to pass:
            && key_len == mph[n].pfx_len + mph[n].sfx_len)

**Comment by dgryski** [comment]
It doesn't matter of there are multiple matches of length n. The actual string values of the prefix and suffix should be compared against their true values from the blob.

**Comment by demerphq** [comment]
On 15 April 2018 at 19:36, Karl Williamson <notifications@github.com> wrote:

> Having now looked at the generated code, my intuition was wrong in the
> specifics, but correct in that there is a missing length check. I haven't
> looked at how the tables are generated, but there are an infinite number of
> possible input strings that will hash to any given bucket. And all but the
> desired one need to be excluded. Hopefully the tables are constructed so
> that no other string of length n can end up in the same bucket as our
> desired string of length n. But we need to exclude those of different
> lengths. Adding this conditional to the test that determines if the lookup
> found anything causes all my tests to pass:
> && key_len == mph[n].pfx_len + mph[n].sfx_len)
>
Yes, I forgot to add that clause. We have to check the length as we use
memcmp() on the prefix and suffix, and we do not include a terminator
character like a null in the strings, so we need to make sure that the
characters we check cover the string exactly. If we happened to be unlucky
enough to have "foo-suffix" hash to the same slot (twice!) as "foo", then
the two memcmp's will pass, but the length check wont.

Anyway, all of this is upstream already.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dgryski** [comment]
If the table is constructed properly, there should be no collisions. That's what makes it a perfect hash. :)

**Comment by demerphq** [comment]
On 15 April 2018 at 22:48, Damian Gryski <notifications@github.com> wrote:

> If the table is constructed properly, there should be no collisions.
> That's what makes it a perfect hash. :)
>

I cant tell who you are replying to. But obviously any hash is going to
have to deal with collisions, a perfect hash only guarantees no collisions
for the keys it /stores/ not all keys, it always has to do the final
comparison against the actual key if it wants certainty.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dgryski** [comment]
My comments was a out foo and foo-suffix mapping to the same slot.

Where is "upstream" for this code?

**Comment by demerphq** [comment]
On 15 April 2018 at 23:57, Damian Gryski <notifications@github.com> wrote:

> My comments was a out foo and foo-suffix mapping to the same slot.
>
> Where is "upstream" for this code?
>

It is mph.pl and related files in this repo.

I think there is a misunderstanding. foo and foo-suffix dont /map/ to the
same slot. 'foo-suffix' isnt a stored key.

However Karl /was/ able to find a "foo" and a "suffix" such that "foo" and
"foosuffix" happened to end up looking at the same final bucket, where the
final string comparison check was for "foo" /without/ checking the length,
and since "foo" is a proper prefix of "foosuffix" it "accidentally" passed.
Had the length been checked properly it would not have matched.

Had the hash actually stored "foo" and "foosuffix" then it would NOT have
collided. It was only because "foosuffix" was NOT stored in the hash that
any collision was possible, and it was quite fortunate for Karl that he
found a suffix that actually landed in the right place such that the bug
about the length was tickled.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dgryski** [comment]
Ah yes, that makes sense now. Thanks.

**Comment by demerphq** [comment]
On 16 April 2018 at 00:05, Damian Gryski <notifications@github.com> wrote:

> Ah yes, that makes sense now. Thanks.
>

Note if the keys were stored in a more typical fashion, with a null
terminator for instance, this would not have happened, or obviously if we
had checked the key-length properly. :-)

Yves
